spring:
  datasource:
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.93.130:3306/springboot_test?useSSL=false&&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root

  #RabbitMq配置信息
  rabbitmq:
    host: 49.234.93.130
    port: 5672
    username: heima
    password: heima
    virtual-host: /itcast
  redis:
    port: 6379
    host: 49.234.93.130
    timeout: 5000
    lettuce:
      pool:
        max-active: 500
        max-wait: 500
        max-idle: 500
        min-idle: 0


mybatis:
  #配置实体类别名包路径
  type-aliases-package: com.itheima.pojo
  #配置映射文件路径
  #mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志记录级别
logging:
  level:
    com.itheima: debug
    org.springframework: info
server:
  port: 80

