spring:
  datasource:
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.234.93.130:3306/springboot_test?useSSL=false&&serverTimezone=UTC
    username: root
    password: root
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j
  #RabbitMq配置信息
  rabbitmq:
    host: 49.234.93.130
    port: 5672
    username: heima
    password: heima
    virtual-host: /itcast


mybatis:
  #配置实体类别名包路径
  type-aliases-package: com.itheima.pojo
  #配置映射文件路径
  #mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志记录级别
logging:
  level:
    com.itheima: debug
    org.springframework: info
server:
  port: 80

